version: '3.8'
services:
  frontend:
    build:
      context: ./docker/frontend
    ports:
      - "3000:3000"
    volumes:
      - ./apps/frontend:/app
    environment:
      - NODE_ENV=development
  backend:
    build:
      context: ./docker/backend
    ports:
      - "8000:8000"
    volumes:
      - ./apps/backend:/app
    environment:
      - ENV=development 