"""add next_credit_reset column to users table

Revision ID: 6313f6e23a4d
Revises: e6a0c337a621
Create Date: 2025-09-24 16:35:23.598077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6313f6e23a4d'
down_revision: Union[str, Sequence[str], None] = 'e6a0c337a621'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('next_credit_reset', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'next_credit_reset')
    # ### end Alembic commands ###
